image: Visual Studio 2017
version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
  - nuget restore
build:
  verbosity: minimal
artifacts:
  - path: CalcBuddy/bin/Release/bridge
    name: CalcBuddy
deploy_script:
  - git checkout origin/gh-pages
  - git rm -rf .
  - git add CalcBuddy/bin/Release/bridge/*
  - bash -c "git mv -v CalcBuddy/bin/Release/bridge/* ."
  - git commit -m 'deploy script'
  - git push
